# https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel", "ruff"]

[dependency-groups]
dev = [
  "towncrier>=25.8.0"
]
docs = []

[project]
authors = [{name = "gdsfactory", email = "contact@gdsfactory.com"}]
classifiers = [
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13"
]
dependencies = [
  "gdsfactory~=9.45.0",
  "gplugins[sax]~=2.1.0",
  "scikit-rf>=1.0.0",
  "gdsfactoryplus"
]
description = "IHP pdk"
keywords = ["python"]
license = {file = "LICENSE"}
name = "ihp-gdsfactory"
readme = "README.md"
requires-python = ">=3.12,<3.13"
version = "2.0.0"

[project.optional-dependencies]
dev = [
  "pytest",
  "pytest-cov",
  "pytest_regressions",
  'jsondiff',
  "pytest-github-actions-annotate-failures",
  "pre-commit"
]
docs = [
  "jupyter",
  "kwasm",
  "mkdocs-material",
  "mkdocs-with-pdf",
  "nbconvert",
  "mkdocstrings[python]>=0.27.0",
  "zensical>=0.0.40,<0.1.0"
]
simulation = [
  "gsim>=0.0.16; python_version>='3.12'"
]

[tool.codespell]
ignore-words-list = "te,fpr,nd,donot,schem,contnet,Contnet,rady,inout,INOUT,nam,coul,calles,wether,rsource,orginal,delT"
skip = "*.lock,*.svg,*.gds,*.oas,*.lib,ihp/models/ngspice/va/*"

[tool.gdsfactoryplus]
ignore = ["refs/*.py"]
name = "ihp"

[tool.gdsfactoryplus.livewire]
schematic_scale = 0.1

[tool.gdsfactoryplus.pdk]
name = "ihp"

[tool.gdsfactoryplus.sim.x]
max = 15  # 15GHz
min = 1  # 1GHz
name = "f"
num = 4001

[tool.mypy]
python_version = "3.12"
strict = true

[tool.pydocstyle]
add-ignore = ["D100", "D101", "D102", "D103", "D104", "D203", "D405", "D417"]
convention = "google"
inherit = false
match = "(?!test).*\\.py"

[tool.pylsp-mypy]
enabled = true
live_mode = true
strict = true

[tool.pytest.ini_options]
# testpaths = ["IHP/samples", "tests"]
# addopts = --tb=no
# addopts = '--tb=short'
# python_files = ["IHP/samples*.py", "tests/*.py"]
python_files = ["tests/*.py"]
testpaths = ["tests"]

[tool.ruff]
exclude = ["cni/", "ihp/refs/"]
fix = true
force-exclude = true

[tool.ruff.lint]
ignore = [
  "E501",  # line too long, handled by black
  "B008",  # do not perform function calls in argument defaults
  "C901",  # too complex
  "B905",  # `zip()` without an explicit `strict=` parameter
  "C408"  # C408 Unnecessary `dict` call (rewrite as a literal)
]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warnings
  "F",  # pyflakes
  "I",  # isort
  "C",  # flake8-comprehensions
  "B",  # flake8-bugbear
  "UP"
]

[tool.ruff.lint.per-file-ignores]
"ihp/cells/__init__.py" = ["F403"]  # allowing star imports to aggregate cells
"ihp/models/__init__.py" = ["F403"]  # allowing star imports to aggregate cells

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*.csv", "*.yaml", "*.yml", "*.gds", "*.lyp", "*.oas", "*.lyt", "*.dat", "*.nc", "*.svg", '*.GDS', "*.json", "*.txt", "*.lib", "*.va", "*.include", "*.h"]

[tool.setuptools.packages.find]
include = ["ihp", "ihp.*", "cni", "cni.*"]
where = ["."]

[tool.tbump]

[[tool.tbump.before_commit]]
cmd = "towncrier build --yes --version {new_version}"
name = "create & check changelog"

[[tool.tbump.before_commit]]
cmd = "git add CHANGELOG.md"
name = "create & check changelog"

[[tool.tbump.before_commit]]
cmd = "grep -q -F {new_version} CHANGELOG.md"
name = "create & check changelog"

[[tool.tbump.file]]
src = "pyproject.toml"

[[tool.tbump.file]]
src = "ihp/__init__.py"

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[tool.tbump.version]
current = "2.0.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[tool.towncrier]
directory = ".changelog.d"
filename = "CHANGELOG.md"
issue_format = "[#{issue}](https://github.com/gdsfactory/ihp/issues/{issue})"
package = "gdsfactory"
start_string = "<!-- towncrier release notes start -->\n"
template = ".changelog.d/changelog_template.jinja"
title_format = "## [{version}](https://github.com/gdsfactory/ihp/releases/tag/v{version}) - {project_date}"
underlines = ["", "", ""]

[[tool.towncrier.type]]
directory = "security"
name = "Security"
showcontent = true

[[tool.towncrier.type]]
directory = "removed"
name = "Removed"
showcontent = true

[[tool.towncrier.type]]
directory = "deprecated"
name = "Deprecated"
showcontent = true

[[tool.towncrier.type]]
directory = "added"
name = "Added"
showcontent = true

[[tool.towncrier.type]]
directory = "changed"
name = "Changed"
showcontent = true

[[tool.towncrier.type]]
directory = "fixed"
name = "Fixed"
showcontent = true
