"""XOR fuzz tests: pure GDSFactory transistors vs live PyCell reference.

Generates transistor layouts from both the pure GDSFactory code
(ihp.cells.transistors) and the PyCell wrappers (ihp.refs) across a
parameter matrix of W/L/NG, then does layer-by-layer kdb.Region XOR
to verify polygon-exact equivalence.
"""

from __future__ import annotations

import itertools

import klayout.db as kdb
import pytest

from ihp import PDK
from ihp import refs as pycell
from ihp.cells.fet_transistors import nmos, nmos_hv, pmos, pmos_hv
from ihp.cells.rf_transistors import rfnmos, rfnmos_hv, rfpmos, rfpmos_hv

# -----------------------------------------------------------------------
# Fixtures
# -----------------------------------------------------------------------


@pytest.fixture(autouse=True)
def activate_pdk():
    PDK.activate()


# -----------------------------------------------------------------------
# XOR engine
# -----------------------------------------------------------------------

SKIP_LAYERS = {
    (63, 0),  # TEXT labels — not generated by pure GDSFactory
    (8, 2),  # Metal1pin — port markers, not physical geometry
    (5, 2),  # GatPolypin — port markers, not physical geometry
    (10, 2),  # Metal2pin — port markers, not physical geometry
}


def xor_cells(ref, new):
    """Layer-by-layer kdb.Region XOR. Returns dict of failing layers."""
    kcell_ref = ref._kf_cell if hasattr(ref, "_kf_cell") else ref
    kcell_new = new._kf_cell if hasattr(new, "_kf_cell") else new
    layout_ref = kcell_ref.layout()
    layout_new = kcell_new.layout()
    dbu = layout_ref.dbu

    layers_ref = {}
    for li in layout_ref.layer_indices():
        info = layout_ref.get_info(li)
        key = (info.layer, info.datatype)
        r = kdb.Region(kcell_ref.begin_shapes_rec(li))
        if not r.is_empty():
            layers_ref[key] = r

    layers_new = {}
    for li in layout_new.layer_indices():
        info = layout_new.get_info(li)
        key = (info.layer, info.datatype)
        r = kdb.Region(kcell_new.begin_shapes_rec(li))
        if not r.is_empty():
            layers_new[key] = r

    all_layers = sorted(set(layers_ref) | set(layers_new))
    failures = {}

    for key in all_layers:
        if key in SKIP_LAYERS:
            continue
        in_ref = key in layers_ref
        in_new = key in layers_new
        if in_ref and not in_new:
            failures[key] = "ONLY IN REF"
            continue
        if in_new and not in_ref:
            failures[key] = "ONLY IN NEW"
            continue

        r_ref = layers_ref[key].merged()
        r_new = layers_new[key].merged()
        xor_area = (r_ref ^ r_new).area() * dbu * dbu
        if xor_area > 1e-6:
            failures[key] = (
                f"XOR={xor_area:.6f} um^2 "
                f"(ref={r_ref.area() * dbu * dbu:.4f}, "
                f"new={r_new.area() * dbu * dbu:.4f})"
            )
    return failures


# -----------------------------------------------------------------------
# Test matrices
# -----------------------------------------------------------------------

NMOS_PARAMS = list(
    itertools.product(
        [0.15, 0.22, 0.30, 0.60, 1.0],  # W
        [0.13, 0.25, 0.50],  # L
        [1, 2, 4],  # NG
    )
)

PMOS_PARAMS = list(
    itertools.product(
        [0.15, 0.22, 0.30, 0.60, 1.0],
        [0.13, 0.25, 0.50],
        [1, 2, 4],
    )
)

NMOSHV_PARAMS = list(
    itertools.product(
        [0.30, 0.60, 1.0, 2.0],
        [0.45, 0.70, 1.0],
        [1, 2, 4],
    )
)

PMOSHV_PARAMS = list(
    itertools.product(
        [0.30, 0.60, 1.0, 2.0],
        [0.40, 0.70, 1.0],
        [1, 2, 4],
    )
)


def _param_id(val):
    width, length, ng = val
    return f"W{width}_L{length}_NG{ng}"


# -----------------------------------------------------------------------
# nmos
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng", NMOS_PARAMS, ids=[_param_id(p) for p in NMOS_PARAMS]
)
def test_xor_nmos(width, length, ng):
    ref = pycell.nmos(w=width, l=length, ng=ng)
    new = nmos(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# pmos
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng", PMOS_PARAMS, ids=[_param_id(p) for p in PMOS_PARAMS]
)
def test_xor_pmos(width, length, ng):
    ref = pycell.pmos(w=width, l=length, ng=ng)
    new = pmos(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# nmosHV
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng", NMOSHV_PARAMS, ids=[_param_id(p) for p in NMOSHV_PARAMS]
)
def test_xor_nmosHV(width, length, ng):
    ref = pycell.nmosHV(w=width, l=length, ng=ng)
    new = nmos_hv(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# pmosHV
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng", PMOSHV_PARAMS, ids=[_param_id(p) for p in PMOSHV_PARAMS]
)
def test_xor_pmosHV(width, length, ng):
    ref = pycell.pmosHV(w=width, l=length, ng=ng)
    new = pmos_hv(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# RF MOSFET test matrices
# -----------------------------------------------------------------------

# Geometric parameter sweep (default RF config)
RFNMOS_PARAMS = list(
    itertools.product(
        [0.5, 1.0, 2.0],  # W
        [0.13, 0.50, 0.72],  # L
        [1, 2, 4],  # NG
    )
)

RFPMOS_PARAMS = list(
    itertools.product(
        [0.5, 1.0, 2.0],
        [0.13, 0.50, 0.72],
        [1, 2, 4],
    )
)

RFNMOSHV_PARAMS = list(
    itertools.product(
        [0.5, 1.0, 2.0],
        [0.45, 0.70, 1.0],
        [1, 2, 4],
    )
)

RFPMOSHV_PARAMS = list(
    itertools.product(
        [0.5, 1.0, 2.0],
        [0.40, 0.70, 1.0],
        [1, 2, 4],
    )
)

# RF-specific configuration sweep (fixed W=1.0, L=0.72, NG=1)
RF_CONFIG_PARAMS = list(
    itertools.product(
        [1, 2],  # cnt_rows
        ["Yes", "No"],  # Met2Cont
        ["Yes", "No"],  # gat_ring
        ["Yes", "No", "U", "Top+Bottom"],  # guard_ring
    )
)


def _rf_param_id(val):
    width, length, ng = val
    return f"W{width}_L{length}_NG{ng}"


def _rf_config_id(val):
    cnt_rows, met2, gat, guard = val
    return f"CR{cnt_rows}_M2{met2}_GR{gat}_GD{guard}"


# -----------------------------------------------------------------------
# rfnmos - geometric sweep
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng",
    RFNMOS_PARAMS,
    ids=[_rf_param_id(p) for p in RFNMOS_PARAMS],
)
def test_xor_rfnmos(width, length, ng):
    ref = pycell.rfnmos(w=width, l=length, ng=ng)
    new = rfnmos(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# rfnmos - RF config sweep
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "cnt_rows,met2_cont,gat_ring_val,guard_ring_val",
    RF_CONFIG_PARAMS,
    ids=[_rf_config_id(p) for p in RF_CONFIG_PARAMS],
)
def test_xor_rfnmos_config(cnt_rows, met2_cont, gat_ring_val, guard_ring_val):
    ref = pycell.rfnmos(
        w=1.0,
        l=0.72,
        ng=1,
        cnt_rows=cnt_rows,
        Met2Cont=met2_cont,
        gat_ring=gat_ring_val,
        guard_ring=guard_ring_val,
    )
    new = rfnmos(
        width=1.0,
        length=0.72,
        nf=1,
        cnt_rows=cnt_rows,
        met2_cont=(met2_cont == "Yes"),
        gat_ring=(gat_ring_val == "Yes"),
        guard_ring=guard_ring_val,
    )
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# rfpmos - geometric sweep
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng",
    RFPMOS_PARAMS,
    ids=[_rf_param_id(p) for p in RFPMOS_PARAMS],
)
def test_xor_rfpmos(width, length, ng):
    ref = pycell.rfpmos(w=width, l=length, ng=ng)
    new = rfpmos(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# rfpmos - RF config sweep
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "cnt_rows,met2_cont,gat_ring_val,guard_ring_val",
    RF_CONFIG_PARAMS,
    ids=[_rf_config_id(p) for p in RF_CONFIG_PARAMS],
)
def test_xor_rfpmos_config(cnt_rows, met2_cont, gat_ring_val, guard_ring_val):
    ref = pycell.rfpmos(
        w=1.0,
        l=0.72,
        ng=1,
        cnt_rows=cnt_rows,
        Met2Cont=met2_cont,
        gat_ring=gat_ring_val,
        guard_ring=guard_ring_val,
    )
    new = rfpmos(
        width=1.0,
        length=0.72,
        nf=1,
        cnt_rows=cnt_rows,
        met2_cont=(met2_cont == "Yes"),
        gat_ring=(gat_ring_val == "Yes"),
        guard_ring=guard_ring_val,
    )
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# rfnmosHV - geometric sweep
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng",
    RFNMOSHV_PARAMS,
    ids=[_rf_param_id(p) for p in RFNMOSHV_PARAMS],
)
def test_xor_rfnmosHV(width, length, ng):
    ref = pycell.rfnmosHV(w=width, l=length, ng=ng)
    new = rfnmos_hv(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# rfnmosHV - RF config sweep
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "cnt_rows,met2_cont,gat_ring_val,guard_ring_val",
    RF_CONFIG_PARAMS,
    ids=[_rf_config_id(p) for p in RF_CONFIG_PARAMS],
)
def test_xor_rfnmosHV_config(cnt_rows, met2_cont, gat_ring_val, guard_ring_val):
    ref = pycell.rfnmosHV(
        w=1.0,
        l=0.72,
        ng=1,
        cnt_rows=cnt_rows,
        Met2Cont=met2_cont,
        gat_ring=gat_ring_val,
        guard_ring=guard_ring_val,
    )
    new = rfnmos_hv(
        width=1.0,
        length=0.72,
        nf=1,
        cnt_rows=cnt_rows,
        met2_cont=(met2_cont == "Yes"),
        gat_ring=(gat_ring_val == "Yes"),
        guard_ring=guard_ring_val,
    )
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# rfpmosHV - geometric sweep
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "width,length,ng",
    RFPMOSHV_PARAMS,
    ids=[_rf_param_id(p) for p in RFPMOSHV_PARAMS],
)
def test_xor_rfpmosHV(width, length, ng):
    ref = pycell.rfpmosHV(w=width, l=length, ng=ng)
    new = rfpmos_hv(width=width, length=length, nf=ng)
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )


# -----------------------------------------------------------------------
# rfpmosHV - RF config sweep
# -----------------------------------------------------------------------


@pytest.mark.parametrize(
    "cnt_rows,met2_cont,gat_ring_val,guard_ring_val",
    RF_CONFIG_PARAMS,
    ids=[_rf_config_id(p) for p in RF_CONFIG_PARAMS],
)
def test_xor_rfpmosHV_config(cnt_rows, met2_cont, gat_ring_val, guard_ring_val):
    ref = pycell.rfpmosHV(
        w=1.0,
        l=0.72,
        ng=1,
        cnt_rows=cnt_rows,
        Met2Cont=met2_cont,
        gat_ring=gat_ring_val,
        guard_ring=guard_ring_val,
    )
    new = rfpmos_hv(
        width=1.0,
        length=0.72,
        nf=1,
        cnt_rows=cnt_rows,
        met2_cont=(met2_cont == "Yes"),
        gat_ring=(gat_ring_val == "Yes"),
        guard_ring=guard_ring_val,
    )
    failures = xor_cells(ref, new)
    assert not failures, "\n".join(
        f"  [{k[0]:3d}/{k[1]}] {v}" for k, v in failures.items()
    )
