#!/usr/bin/env python3
"""Convert the IHP SG13G2 ngspice device models to VACASK (Spectre-dialect) format.

This reuses VACASK's own ``ng2vclib`` converter and the configuration defined in
VACASK's ``sg13g2tovc`` orchestration script, but takes ONLY the device-model
``.lib`` conversion. We deliberately SKIP everything the official script does
beyond that:

* No VA -> OSDI precompilation (no ``openvaf``). Instead we ship the Verilog-A
  sources (under ``ihp/models/ngspice/va/``) and generate an *on-the-fly* common
  include that ``load``s them, so VACASK compiles ``.osdi`` on the user's machine
  via the ``openvaf-r`` bundled in ``vacask-bin``. This keeps the wheel
  cross-platform and binary-free.
* No xschem symbol conversion, no stdcell/io conversion, no ``.vacaskrc.toml``.

The generated ``sg13g2_vacask_common.lib`` is produced HERE (not via the official
precompile path): it declares ``swsoa``, ``load``s the four shipped Verilog-A
sources, and ``load``s the bundled SPICE-compatible primitive ``.osdi`` modules
(the primitive set is derived from the converter's ``family_map`` usage).

Each converted ``.lib`` carries ``include "sg13g2_vacask_common.lib"`` at its top
(via the converter ``signature``) so it is self-contained: when the netlister
includes a flat device lib the modules come along, and corner libs reach the
common file through the inner ``include "..._mod.lib"`` of each section.

Pinned sources (see PR / Step 0):
    VACASK        codeberg.org/arpadbuermen/VACASK  main @ 25cb29d1bc25847e83fc9161d122374ee845d4e7
    IHP-Open-PDK  github.com/IHP-GmbH/IHP-Open-PDK  main @ 6e27ed59c07060e39252924875625f3d7eb1db49

Invocation:
    VACASK_DIR=/path/to/VACASK PDK_ROOT=/path/to/IHP-Open-PDK \
        python scripts/convert_vacask_models.py

or, with the defaults below (or ``make vacask-models``):
    python scripts/convert_vacask_models.py
"""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# Dev/maintenance inputs only -- nothing at PDK runtime depends on these paths.
VACASK_DIR_ENV = os.environ.get("VACASK_DIR")
PDK_ROOT_ENV = os.environ.get("PDK_ROOT")

if not VACASK_DIR_ENV or not PDK_ROOT_ENV:
    raise ValueError("Both VACASK_DIR and PDK_ROOT environment variables must be set.")

VACASK_DIR = Path(VACASK_DIR_ENV)
PDK_ROOT = Path(PDK_ROOT_ENV)
PDK = os.environ.get("PDK", "ihp-sg13g2")

OUT_DIR = REPO_ROOT / "ihp" / "models" / "vacask" / "models"
COMMON_LIB = "sg13g2_vacask_common.lib"

# The four IHP Verilog-A device sources we ship and compile on the fly. Paths are
# relative to OUT_DIR and resolve into the shipped ihp/models/ngspice/va tree.
# These are NOT in the converter's family_map (they are instantiated as VACASK
# modules directly), so they cannot be derived and are listed explicitly -- they
# mirror VACASK's ``included_va_files`` list.
VA_LOADS = [
    "../../ngspice/va/psp103/psp103.va",
    "../../ngspice/va/psp103/psp103_nqs.va",
    "../../ngspice/va/r3_cmc/r3_cmc.va",
    "../../ngspice/va/mosvar/mosvar.va",
]

SIGNATURE = (
    "// Converted from the IHP SG13G2 PDK ngspice models for VACASK\n"
    "// Generated by scripts/convert_vacask_models.py -- do not edit by hand.\n"
    "\n"
    f'include "{COMMON_LIB}"\n'
)


def _build_cfg(default_config, sg13g2tovc, tech_src, read_process_depth, output_depth):
    """Construct a per-file converter config, mirroring VACASK's sg13g2tovc."""
    cfg = default_config()
    cfg.update(
        {
            "default_model_prefix": "sg13g2_default_mod_",
            "sourcepath": [".", str(tech_src)],
            "read_depth": read_process_depth,
            "process_depth": read_process_depth,
            "output_depth": output_depth,
            "patch": sg13g2tovc.patches,
            "original_case_subckt": True,
            "original_case_model": True,
            "signature": SIGNATURE,
        }
    )
    cfg["family_map"].update(sg13g2tovc.family_map_update)
    cfg["remove_model_params"].update(sg13g2tovc.remove_model_params_update)
    cfg["subckt_multiplier"].update(sg13g2tovc.subckt_multiplier_update)
    return cfg


def main() -> int:
    if not VACASK_DIR.is_dir():
        sys.exit(f"VACASK_DIR does not exist: {VACASK_DIR}")
    if not PDK_ROOT.is_dir():
        sys.exit(f"PDK_ROOT does not exist: {PDK_ROOT}")

    sys.path.insert(0, str(VACASK_DIR / "python"))
    import sg13g2tovc  # noqa: E402  -- reuse its config dicts, do not duplicate
    from ng2vclib.converter import Converter  # noqa: E402
    from ng2vclib.dfl import default_config  # noqa: E402

    tech_src = (PDK_ROOT / PDK / "libs.tech" / "ngspice" / "models").resolve()
    if not tech_src.is_dir():
        sys.exit(f"ngspice models dir not found: {tech_src}")

    # Regenerate fresh: drop any previous (untracked) tree first.
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)

    # Only the device-model .lib rows; skip stdcell/io (the *.inc destinations).
    device_rows = [row for row in sg13g2tovc.tech_files if row[0].endswith(".lib")]

    osdi_files: set[str] = set()
    dflmods: set[tuple[str, str]] = set()

    print(f"Converting {len(device_rows)} device .lib files from {tech_src}")
    for filename, read_process_depth, output_depth, _destpath in device_rows:
        print("  ", filename)
        cfg = _build_cfg(
            default_config, sg13g2tovc, tech_src, read_process_depth, output_depth
        )
        cvt = Converter(cfg, indent=4, debug=0)
        cvt.convert(filename, str(OUT_DIR / filename))

        # Bundled primitive .osdi files needed, derived from used + default models.
        for mname, in_sub in cvt.data["model_usage"]:
            _builtin, _mtype, family, level, version, _params = cvt.data["models"][
                in_sub
            ][mname]
            key = (family, level, version)
            if key in cvt.cfg["family_map"]:
                osdi_files.add(cvt.cfg["family_map"][key][0])
        for mt in cvt.data["default_models_needed"]:
            osdi_file, module = cvt.cfg["default_models"][mt]
            osdi_files.add(osdi_file)
            dflmods.add((mt, module))

    write_common_lib(osdi_files, dflmods, default_model_prefix="sg13g2_default_mod_")
    print(f"Wrote {OUT_DIR / COMMON_LIB}")
    return 0


def write_common_lib(osdi_files, dflmods, default_model_prefix):
    """Generate the on-the-fly common include loaded by every converted lib."""
    lines = [
        "// On-the-fly VACASK common include for the IHP SG13G2 models.",
        "// Generated by scripts/convert_vacask_models.py -- do not edit by hand.",
        "//",
        "// The four Verilog-A sources below are shipped with the PDK and compiled",
        "// to .osdi on first run by the openvaf-r bundled in vacask-bin. The .osdi",
        "// loads are SPICE-compatible primitives bundled in vacask-bin (resolved",
        "// via its module path / SIM_MODULE_PATH at runtime).",
        "",
        "// Disable safe-operating-area checks (the SWSOA .param is stripped from",
        "// the converted MOS libs; see sg13g2tovc patches).",
        "parameters swsoa=0",
        "",
        "// IHP Verilog-A device sources (compiled on the fly):",
    ]
    lines += [f'load "{p}"' for p in VA_LOADS]
    lines.append("")
    lines.append("// vacask-bin bundled SPICE-compatible primitive modules:")
    lines += [f'load "{p}"' for p in sorted(osdi_files)]
    if dflmods:
        lines.append("")
        lines.append("// Default models for unmodeled primitive instances:")
        lines += [
            f"model {default_model_prefix}{mt} {module}"
            for mt, module in sorted(dflmods)
        ]
    lines.append("")
    (OUT_DIR / COMMON_LIB).write_text("\n".join(lines))


if __name__ == "__main__":
    raise SystemExit(main())
